[book]
authors = ["async fn fundamentals Members"]
language = "en"
multilingual = false
src = "."
title = "async fn fundamentals initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/async-fn-fundamentals"

[output.html.fold]
enable = true
level = 0
